### ISSUE TITLE
Please go through the current code

### ISSUE THREAD

**Issue by aaumkar** [ameysatwe/Factory-Model-Project#13]
Please go through the current code and clarify any issues.
Raise issues if comments are not clear.

**Comment by ameysatwe** [comment]
Yup i will dw

**Comment by ameysatwe** [comment]
The code u have written is dangerous af

**Comment by aaumkar** [comment]
Ummm, I am writing some more stuff bro.

**Comment by ameysatwe** [comment]
Should we close this?

**Comment by aaumkar** [comment]
Yeah, you can close, no problem.
