### ISSUE TITLE
Operation aesthetics

### ISSUE THREAD

**Issue by aaumkar** [ameysatwe/Factory-Model-Project#14]
# Small things such as 

* Random delay within each operation.
* Aesthetics of delays.
* Console Outputs
    - TQDM bars if necessary
* Colors in Console if possible

**Comment by ameysatwe** [comment]
Colors are possible with [termcolor](https://pypi.org/project/termcolor/)

**Comment by aaumkar** [comment]
Will look into it.
Cheers!

**Comment by ameysatwe** [comment]
TQDM is nice but lets try to do something away from the console!!!!

**Comment by aaumkar** [comment]
Issue  covered under #11 
Or are we thinking TKinter?

**Comment by ameysatwe** [comment]
Umm lets not use tkinter let it be under #11

**Comment by aaumkar** [comment]
Delays not added, assuming every data dump would take some time already.
Colors added.
